@baseUrl = http://localhost:5001/api/auth
@email = testuser@example.com
@password = Test1234!
@newPassword = NewTest1234!

### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Confirm Email
POST {{baseUrl}}/confirm-email
Content-Type: application/json

{
  "email": "{{email}}",
  "token": "423a1a5b30064c7da60ac1d55b21c5b0"
}

### Login
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Access Token
@accessToken = {{login.response.body.accessToken}}


### Refresh Token
# @name refresh
POST {{baseUrl}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}


### 1. Logout (Without refresh)
POST {{baseUrl}}/logout
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}


### 2. Logout (After refresh)
POST {{baseUrl}}/logout
Content-Type: application/json

{
  "refreshToken": "{{refresh.response.body.refreshToken}}"
}

### Change Password
POST {{baseUrl}}/change-password
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "oldPassword": "{{password}}",
  "newPassword": "{{newPassword}}"
}

### Forgot Password
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
  "email": "{{email}}"
}

### Reset Password
POST {{baseUrl}}/reset-password
Content-Type: application/json

{
  "email": "{{email}}",
  "token": "YOUR_RESET_TOKEN_HERE",
  "newPassword": "{{newPassword}}"
}