@baseUrl = http://localhost:5002/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE4YzcwYzcyLWJkYTItNDlmYy05ZDhkLTFmMWVkODNmZTNlMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc4NzY1ODUzOCwiaXNzIjoiaXR1YmUiLCJhdWQiOiJpdHViZSJ9.IyKrrcrW-vmDdVdeYnpwBF2mH9mhrpfEYCh1rcHY8lk

### Get User
GET {{baseUrl}}/users/a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1
Content-Type: application/json

### Get Channel
GET {{baseUrl}}/channels/a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1
Content-Type: application/json

### Update Channel
PUT {{baseUrl}}/channels/a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "My Awesome Channel",
  "description": "This is my channel description",
  "avatarBucket": null,
  "avatarKey": null,
  "bannerBucket": null,
  "bannerKey": null
}

### Subscribe to Channel
POST {{baseUrl}}/subscriptions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "targetChannelId": "a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1"
}

### Unsubscribe from Channel
DELETE {{baseUrl}}/subscriptions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "targetChannelId": "a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1"
}

### Ban User (Moderator/Admin only)
POST {{baseUrl}}/moderation/users/USER_ID_HERE/ban
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "reason": "Violation of community guidelines",
  "expiresAt": "2026-08-01T00:00:00Z"
}

### Unban User (Moderator/Admin only)
DELETE {{baseUrl}}/moderation/users/a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1/ban
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Change Role (Admin only)
PATCH {{baseUrl}}/users/a8c70c72-bda2-49fc-9d8d-1f1ed83fe3e1/role
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "role": 1
}
